## Step 1: Array Creation

In [3]:
import numpy as np
#from a python list
a = np.array([1,2,3,4,5])
print(a)
# 2D array (matrix)
b = np.array([[1,2,3],[4,5,6]])
print(b)
# built-in generators
zeros = np.zeros((2,3))
ones = np.ones((3,3))
rng = np.arange(0,10,2)
lin = np.linspace(0,1,5)
identity = np.eye(3)
print("Zeros:\n",zeros)
print("Ones:\n",ones)
print("Range:",rng)
print("Linspace:",lin)
print("Idnetity:",identity)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Idnetity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Step 2: Indexing and Slicing

In [4]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print("First element:", arr[0])      # 10
print("Last element:", arr[-1])      # 50

# Slicing
print("Elements 1 to 3:", arr[1:4])  # [20 30 40]
print("First 3 elements:", arr[:3])  # [10 20 30]
print("Every 2nd element:", arr[::2]) # [10 30 50]

# 2D array indexing
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D array:\n", mat)
print("Row 1, Col 2:", mat[1, 2])     # 6
print("All rows, Col 0:", mat[:, 0])  # [1 4 7]
print("Sub-matrix:\n", mat[0:2, 1:3])

# Boolean indexing
print("\nElements greater than 20:", arr[arr > 20])  # [30 40 50]

First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
First 3 elements: [10 20 30]
Every 2nd element: [10 30 50]

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row 1, Col 2: 6
All rows, Col 0: [1 4 7]
Sub-matrix:
 [[2 3]
 [5 6]]

Elements greater than 20: [30 40 50]


##Step3:Mathematical,Axis-wise,Statistical Operations

In [5]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print("Original data:\n", data)

print("\nAdd 10 to every element:\n", data + 10)
print("Multiply every element by 2:\n", data * 2)
print("Square root of every element:\n", np.sqrt(data))

# Axis-wise operations
# axis=0 -> operation goes DOWN the columns
# axis=1 -> operation goes ACROSS the rows
print("\nSum of each column (axis=0):", data.sum(axis=0))
print("Sum of each row (axis=1):", data.sum(axis=1))

# Statistical operations
print("\nMean (average):", data.mean())
print("Standard deviation:", data.std())
print("Maximum value:", data.max())
print("Minimum value:", data.min())
print("Median:", np.median(data))

Original data:
 [[1 2 3]
 [4 5 6]]

Add 10 to every element:
 [[11 12 13]
 [14 15 16]]
Multiply every element by 2:
 [[ 2  4  6]
 [ 8 10 12]]
Square root of every element:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

Sum of each column (axis=0): [5 7 9]
Sum of each row (axis=1): [ 6 15]

Mean (average): 3.5
Standard deviation: 1.707825127659933
Maximum value: 6
Minimum value: 1
Median: 3.5


##Step4:Reshaping and Broadcasting

In [6]:
arr = np.arange(12)   # creates [0,1,2,...,11]
print("Original 1D array:", arr)

# Reshaping: change the shape WITHOUT changing the data
reshaped = arr.reshape(3, 4)   # 3 rows, 4 columns
print("\nReshaped into 3x4:\n", reshaped)

reshaped2 = arr.reshape(4, 3)  # 4 rows, 3 columns
print("\nReshaped into 4x3:\n", reshaped2)

flattened = reshaped.flatten()  # back to 1D
print("\nFlattened back to 1D:", flattened)

# Broadcasting: operating on arrays of DIFFERENT shapes
a = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2,3)
b = np.array([10, 20, 30])
print("\nArray a (2x3):\n", a)
print("Array b (1x3):", b)
print("a + b (b is broadcast across every row):\n", a + b)

# Another broadcasting example: adding a single number
c = a + 100
print("\na + 100 (single number broadcast to all elements):\n", c)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped into 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped into 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Flattened back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Array a (2x3):
 [[1 2 3]
 [4 5 6]]
Array b (1x3): [10 20 30]
a + b (b is broadcast across every row):
 [[11 22 33]
 [14 25 36]]

a + 100 (single number broadcast to all elements):
 [[101 102 103]
 [104 105 106]]


##Step5: Save/Load Operations

In [7]:
arr = np.array([1, 2, 3, 4, 5])

# Save a single array to a .npy file
np.save('my_array.npy', arr)
print("Array saved as my_array.npy")

# Load it back
loaded = np.load('my_array.npy')
print("Loaded array:", loaded)

# Save MULTIPLE arrays together in one .npz file
np.savez('multi_arrays.npz', a=arr, b=reshaped)
print("\nMultiple arrays saved as multi_arrays.npz")

# Load the .npz file back
data = np.load('multi_arrays.npz')
print("Loaded 'a':", data['a'])
print("Loaded 'b':\n", data['b'])

# Save as a plain text/CSV file (human-readable)
np.savetxt('array.csv', arr, delimiter=',')
print("\nArray saved as array.csv")

# Load it back from CSV
loaded_csv = np.loadtxt('array.csv', delimiter=',')
print("Loaded from CSV:", loaded_csv)

Array saved as my_array.npy
Loaded array: [1 2 3 4 5]

Multiple arrays saved as multi_arrays.npz
Loaded 'a': [1 2 3 4 5]
Loaded 'b':
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array saved as array.csv
Loaded from CSV: [1. 2. 3. 4. 5.]


##Step6:Numpy vs Standard Python performance

In [8]:
import time

size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)

# --- Pure Python loop ---
start = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time() - start
print("Python list time:", py_time, "seconds")

# --- NumPy vectorized operation ---
start = time.time()
np_result = np_array * 2
np_time = time.time() - start
print("NumPy array time:", np_time, "seconds")

# --- Comparison ---
print("\nNumPy was", round(py_time / np_time, 2), "times faster than pure Python")

Python list time: 0.05618095397949219 seconds
NumPy array time: 0.004053592681884766 seconds

NumPy was 13.86 times faster than pure Python
